#!/usr/bin/env python3
"""
sl-ot-tools — CLI for Silver Lake Operating Technology tools.

Commands:
    init company <slug>      Create a new company repo structure
    init engagement <name>   Create a new engagement directory
    setup                    Update skills and viewer (safe to re-run)
    setup --reconfigure      Re-prompt for user config values
    settings                 Configure user-level settings (~/.config/sl-ot-tools/)
    check                    Verify installation and config
    generate-viewer          Regenerate org chart viewer from template
"""

import json
import os
import shutil
import sys
from pathlib import Path

from . import __version__
from .config.resolver import (
    find_company_dir,
    find_engagement_dir,
    find_local_dir,
    find_repo_root,
    load_json,
    load_user_config,
)


def _get_templates_dir():
    return Path(__file__).parent / "templates"


def _get_viewer_template():
    return Path(__file__).parent / "viewer" / "org_chart_template.html"


# ── init company ──────────────────────────────────────────────

def cmd_init_company(slug):
    """Create a new company repo structure."""
    target = Path.cwd() / slug if not Path(slug).is_absolute() else Path(slug)
    if target.exists() and any(target.iterdir()):
        print(f"ERROR: Directory {target} already exists and is not empty")
        sys.exit(1)

    company_dir = target / "_company"
    local_dir = target / ".local"

    company_dir.mkdir(parents=True, exist_ok=True)
    local_dir.mkdir(parents=True, exist_ok=True)
    (target / ".claude" / "commands").mkdir(parents=True, exist_ok=True)

    # company_config.json
    company_config = {
        "company": slug.replace("-", " ").title(),
        "domains": [],
        "domain_labels": {},
        "skip_senders": [],
        "contractor_patterns": ["^[a-z]+x\\."],
        "location_hints": [],
    }
    _write_json(company_dir / "company_config.json", company_config)

    # people_config.json
    people_config = {
        "org_chart": "org_chart.json",
        "checkpoint": "people_checkpoint.json",
        "ignore_list": "people_ignore.json",
    }
    _write_json(company_dir / "people_config.json", people_config)

    # Empty org_chart.json
    org_chart = {
        "company": company_config["company"],
        "generated": "",
        "leadership": [],
        "people": [],
        "external_ecosystem": {},
        "key_programs": [],
    }
    _write_json(company_dir / "org_chart.json", org_chart)

    # Empty checkpoints
    _write_json(company_dir / "people_checkpoint.json", {
        "last_updated": None,
        "processed_ids": [],
        "total_processed": 0,
    })
    _write_json(company_dir / "people_ignore.json", {"ignored": []})

    # .gitignore
    gitignore = """# OS files
.DS_Store
Thumbs.db
Desktop.ini

# Binary/Office files — these live in SharePoint, not git
# Use sync scripts to pull them locally
*.docx
*.xlsx
*.pptx
*.pdf
*.zip

# Office temp/lock files
~$*
*.tmp

# Zone.Identifier files (Windows/WSL artifacts)
*.Zone.Identifier
*:Zone.Identifier

# Per-user local state (gitignored)
.local/

# Claude Code (keep commands/ for shared skills)
.claude/*
!.claude/commands/

# OneDrive conflict files
*-conflict-*
*(1).*

# Python
__pycache__/
*.pyc
"""
    (target / ".gitignore").write_text(gitignore)

    # CLAUDE.md
    claude_md = f"""# {company_config['company']}

This is a Silver Lake portfolio company repo managed with sl-ot-tools.

## Structure

- `_company/` — Company-level shared data (org chart, configs, people data)
- `.local/` — Per-user config and ephemeral data (gitignored)
- `.claude/commands/` — Claude Code skills (generated by `sl-ot-tools setup`)
- Each top-level directory (other than the above) is an engagement

## Tools

All tools are installed via `pip install sl-ot-tools` and available on PATH:
- `sl-ot-sync` — Bidirectional sync with SharePoint
- `sl-ot-read-emails` — Read emails from Outlook
- `sl-ot-process-people` — Scan emails for people signals
- `sl-ot-md2docx` — Convert markdown to Word documents

## Setup

Run `sl-ot-tools setup` after cloning to configure local paths and install skills.
"""
    (target / "CLAUDE.md").write_text(claude_md)

    print(f"Created company repo: {target}")
    print(f"  _company/company_config.json  — edit domains, labels, patterns")
    print(f"  _company/org_chart.json       — seed with known leadership")
    print(f"  .gitignore                    — configured")
    print()
    print("Next steps:")
    print(f"  cd {slug}")
    print(f"  # Edit _company/company_config.json")
    print(f"  sl-ot-tools init engagement <name>")
    print(f"  sl-ot-tools setup")


def cmd_init_engagement(name):
    """Create a new engagement directory."""
    repo_root = find_repo_root()
    if not repo_root:
        print("ERROR: Not inside a company repo (_company/ not found)")
        print("Run 'sl-ot-tools init company <slug>' first")
        sys.exit(1)

    eng_dir = repo_root / name
    if eng_dir.exists() and any(eng_dir.iterdir()):
        print(f"ERROR: Directory {eng_dir} already exists and is not empty")
        sys.exit(1)

    eng_dir.mkdir(parents=True, exist_ok=True)

    # engagement_config.json
    eng_config = {
        "engagement": name,
        "engagement_label": name.replace("-", " ").title(),
        "knowledge_types": [
            "decision", "technical", "status", "action",
            "blocker", "timeline", "budget", "risk",
        ],
        "skip_senders": [],
        "workstreams": {
            "general": {
                "label": "01-General",
                "output_dir": "01-General",
                "keywords_subject": [],
                "keywords_body": [],
                "programs": [],
                "people_associations": [],
            }
        },
    }
    _write_json(eng_dir / "engagement_config.json", eng_config)

    # sync-map.conf
    sync_conf = f"""# sync-map.conf — Folder mappings for {name}
#
# LOCAL_ROOT: auto-resolved from this file's parent directory
# REMOTE_ROOT: resolved from .local/user-config.json
#
# Format: LOCAL_PATH | REMOTE_PATH | LABEL
# See sl-ot-tools docs for prefix options (push:, pull:, file:)

# Company-level data (pushed to SharePoint)
push:file:../_company/org_chart.json | People | Org Chart JSON (push-only)
push:file:../_company/org_chart_viewer.html | People | Org Chart Viewer (push-only)

# Engagement workstreams — add mappings below
# 01-General | General | General workstream
"""
    (eng_dir / "sync-map.conf").write_text(sync_conf)

    # Wrapper scripts
    sync_push = f"""#!/bin/bash
# Push locally-created files to SharePoint for the {name} engagement.
exec sl-ot-sync push -c "$(dirname "$0")/sync-map.conf" "$@"
"""
    sync_pull = f"""#!/bin/bash
# Pull latest from SharePoint for the {name} engagement.
exec sl-ot-sync pull -c "$(dirname "$0")/sync-map.conf" "$@"
"""
    (eng_dir / "sync_to_sharepoint.sh").write_text(sync_push)
    (eng_dir / "sync_from_sharepoint.sh").write_text(sync_pull)
    os.chmod(eng_dir / "sync_to_sharepoint.sh", 0o755)
    os.chmod(eng_dir / "sync_from_sharepoint.sh", 0o755)

    # Default workstream directory
    (eng_dir / "01-General").mkdir(exist_ok=True)

    print(f"Created engagement: {eng_dir}")
    print(f"  engagement_config.json  — edit workstreams, keywords, people")
    print(f"  sync-map.conf           — add SharePoint folder mappings")
    print()
    print("Next steps:")
    print(f"  # Edit {name}/engagement_config.json")
    print(f"  # Edit {name}/sync-map.conf")
    print(f"  sl-ot-tools setup")


# ── setup ─────────────────────────────────────────────────────

def cmd_setup(reconfigure=False, force_skills=False):
    """Interactive setup: user config, skills, viewer.

    If user config already exists, skips interactive prompts and just
    updates skills + viewer. Use --reconfigure to re-prompt for config.
    """
    repo_root = find_repo_root()
    if not repo_root:
        print("ERROR: Not inside a company repo (_company/ not found)")
        sys.exit(1)

    company_dir = repo_root / "_company"
    local_dir = repo_root / ".local"
    local_dir.mkdir(exist_ok=True)

    # Load existing user config or create new
    user_config_path = local_dir / "user-config.json"
    has_existing_config = user_config_path.exists()

    if has_existing_config:
        user_config = load_json(user_config_path)
    else:
        user_config = {}

    # Find all engagements
    engagements = []
    for p in repo_root.iterdir():
        if p.is_dir() and (p / "engagement_config.json").exists():
            engagements.append(p.name)

    if not has_existing_config or reconfigure:
        # Interactive config prompts
        if has_existing_config:
            print(f"Reconfiguring: {user_config_path}")
        print()

        # Prompt for user name
        current_user = user_config.get("user", os.environ.get("USER", ""))
        user = input(f"User name [{current_user}]: ").strip() or current_user
        user_config["user"] = user

        # Prompt for OneDrive root
        current_root = user_config.get("onedrive_root", "")
        print()
        print("OneDrive root path (the folder where SharePoint shortcuts are mounted).")
        print("Example: /mnt/c/Users/jane.doe/OneDrive - Silver Lake/OT Sharepoint Shortcuts")
        onedrive_root = input(f"OneDrive root [{current_root}]: ").strip() or current_root
        user_config["onedrive_root"] = onedrive_root

        # Prompt for per-engagement SharePoint mappings
        mappings = user_config.get("onedrive_mappings", {})
        if engagements:
            print()
            print("SharePoint mappings (relative path under OneDrive root for each engagement).")
            print("Example: Companies/Altera/Enclave")
            for eng in sorted(engagements):
                current_mapping = mappings.get(eng, "")
                mapping = input(f"  {eng} [{current_mapping}]: ").strip() or current_mapping
                if mapping:
                    mappings[eng] = mapping
        user_config["onedrive_mappings"] = mappings

        # Write user config
        _write_json(user_config_path, user_config)
        print(f"\nSaved: {user_config_path}")
    else:
        print(f"Using existing config: {user_config_path}")
        print(f"  (run 'sl-ot-tools setup --reconfigure' to change)")

    # Mention settings if not configured
    from .config.settings import SETTINGS_FILE
    if not SETTINGS_FILE.exists():
        print()
        print("Tip: Run 'sl-ot-tools settings' to configure user-level preferences")
        print("     (timezone, PowerShell path, Word template, email defaults)")

    # Install skills
    _install_skills(repo_root, engagements, force=force_skills)

    # Generate viewer
    _generate_viewer(company_dir)

    # Verify
    print()
    cmd_check(quiet=False)


# ── check ─────────────────────────────────────────────────────

def cmd_check(quiet=False):
    """Verify installation and config."""
    issues = []
    ok_items = []

    # Check package version
    ok_items.append(f"sl-ot-tools v{__version__}")

    # Check repo structure
    repo_root = find_repo_root()
    if not repo_root:
        issues.append("Not inside a company repo (_company/ not found)")
        if not quiet:
            _print_check_results(ok_items, issues)
        return len(issues) == 0

    ok_items.append(f"Repo root: {repo_root}")

    company_dir = repo_root / "_company"

    # Check configs exist
    for cfg in ["company_config.json", "people_config.json", "org_chart.json"]:
        path = company_dir / cfg
        if path.exists():
            try:
                load_json(path)
                ok_items.append(f"Valid JSON: _company/{cfg}")
            except Exception as e:
                issues.append(f"Invalid JSON: _company/{cfg} — {e}")
        else:
            issues.append(f"Missing: _company/{cfg}")

    # Check user config
    local_dir = repo_root / ".local"
    user_config_path = local_dir / "user-config.json"
    if user_config_path.exists():
        try:
            uc = load_json(user_config_path)
            ok_items.append(f"User config: {uc.get('user', '?')}")

            # Check OneDrive root exists
            odr = uc.get("onedrive_root", "")
            if odr and os.path.isdir(odr):
                ok_items.append(f"OneDrive root exists: {odr}")
            elif odr:
                issues.append(f"OneDrive root not found: {odr}")

            # Check engagement mappings resolve
            for eng, rel_path in uc.get("onedrive_mappings", {}).items():
                full_path = os.path.join(odr, rel_path)
                if os.path.isdir(full_path):
                    ok_items.append(f"SharePoint path exists: {eng} → {rel_path}")
                else:
                    issues.append(f"SharePoint path not found: {eng} → {full_path}")
        except Exception as e:
            issues.append(f"Invalid user config: {e}")
    else:
        issues.append("Missing: .local/user-config.json — run 'sl-ot-tools setup'")

    # Check engagements
    for p in sorted(repo_root.iterdir()):
        if p.is_dir() and (p / "engagement_config.json").exists():
            try:
                load_json(p / "engagement_config.json")
                ok_items.append(f"Engagement: {p.name}")
            except Exception as e:
                issues.append(f"Invalid engagement config: {p.name} — {e}")

    # Check viewer
    viewer_path = company_dir / "org_chart_viewer.html"
    if viewer_path.exists():
        ok_items.append("Viewer: org_chart_viewer.html")
    else:
        issues.append("Missing: _company/org_chart_viewer.html — run 'sl-ot-tools generate-viewer'")

    # Check skills
    skills_dir = repo_root / ".claude" / "commands"
    if skills_dir.exists() and any(skills_dir.iterdir()):
        skill_count = len(list(skills_dir.glob("*.md")))
        ok_items.append(f"Skills installed: {skill_count}")
    else:
        issues.append("No skills installed — run 'sl-ot-tools setup'")

    if not quiet:
        _print_check_results(ok_items, issues)

    return len(issues) == 0


def _print_check_results(ok_items, issues):
    print("\n=== sl-ot-tools check ===")
    for item in ok_items:
        print(f"  OK  {item}")
    for issue in issues:
        print(f"  !!  {issue}")
    print()
    if issues:
        print(f"{len(issues)} issue(s) found.")
    else:
        print("All checks passed.")


# ── generate-viewer ───────────────────────────────────────────

def cmd_generate_viewer():
    """Regenerate org chart viewer from template."""
    company_dir = find_company_dir()
    if not company_dir:
        print("ERROR: Not inside a company repo (_company/ not found)")
        sys.exit(1)

    _generate_viewer(company_dir)


def _generate_viewer(company_dir):
    """Generate viewer HTML from template + company config."""
    template_path = _get_viewer_template()
    if not template_path.exists():
        print(f"WARNING: Viewer template not found at {template_path}")
        return

    # Get company name from config
    company_config_path = company_dir / "company_config.json"
    company_name = "Company"
    if company_config_path.exists():
        try:
            cc = load_json(company_config_path)
            company_name = cc.get("company", "Company")
        except Exception:
            pass

    template = template_path.read_text(encoding="utf-8")
    html = template.replace("{{COMPANY_NAME}}", company_name)

    output_path = company_dir / "org_chart_viewer.html"
    output_path.write_text(html, encoding="utf-8")
    print(f"Generated viewer: {output_path}")

    # Generate engagement_map.json from engagement configs
    _generate_engagement_map(company_dir)


def _generate_engagement_map(company_dir):
    """Scan all engagement_config.json files and build engagement_map.json."""
    repo_root = company_dir.parent
    engagements = []

    for p in sorted(repo_root.iterdir()):
        if not p.is_dir():
            continue
        cfg_path = p / "engagement_config.json"
        if not cfg_path.exists():
            continue

        try:
            cfg = load_json(cfg_path)
        except Exception as e:
            print(f"  WARNING: Skipping {p.name}/engagement_config.json: {e}")
            continue

        eng_key = cfg.get("engagement", p.name)
        eng_label = cfg.get("engagement_label", eng_key.replace("-", " ").title())
        eng_sp_url = cfg.get("sharepoint_url", "")

        workstreams = []
        for ws_key, ws_data in cfg.get("workstreams", {}).items():
            if not isinstance(ws_data, dict):
                continue
            ws_entry = {
                "key": ws_key,
                "label": ws_data.get("label", ws_key),
                "programs": ws_data.get("programs", []),
                "people_associations": ws_data.get("people_associations", []),
            }
            ws_sp_url = ws_data.get("sharepoint_url", "")
            if ws_sp_url:
                ws_entry["sharepoint_url"] = ws_sp_url
            workstreams.append(ws_entry)

        eng_entry = {
            "key": eng_key,
            "label": eng_label,
            "workstreams": workstreams,
        }
        if eng_sp_url:
            eng_entry["sharepoint_url"] = eng_sp_url
        engagements.append(eng_entry)

    if engagements:
        engagement_map = {"engagements": engagements}
        output_path = company_dir / "engagement_map.json"
        _write_json(output_path, engagement_map)
        print(f"Generated engagement map: {output_path} ({len(engagements)} engagement(s))")
    else:
        print("  No engagement configs found — skipping engagement_map.json")


# ── skill installation ────────────────────────────────────────

def _install_skills(repo_root, engagements, force=False):
    """Install Claude Code skills from templates.

    Detects user-modified skill files and preserves them (with a warning)
    unless force=True. Custom skills (files not matching any template)
    are always preserved.
    """
    templates_dir = _get_templates_dir() / "commands"
    target_dir = repo_root / ".claude" / "commands"
    target_dir.mkdir(parents=True, exist_ok=True)

    company_dir = repo_root / "_company"
    company_name = "Company"
    cc_path = company_dir / "company_config.json"
    if cc_path.exists():
        try:
            cc = load_json(cc_path)
            company_name = cc.get("company", "Company")
        except Exception:
            pass

    if not templates_dir.exists():
        print("WARNING: Skill templates not found")
        return

    from .config.settings import PROMPTS_DIR

    # Build engagement resolution block for skills that operate per-engagement
    if engagements:
        eng_list = ", ".join(f"`{e}`" for e in sorted(engagements))
        engagement_resolution = (
            f"## Engagement resolution\n\n"
            f"This skill operates within an engagement directory. "
            f"Available engagements: {eng_list}.\n\n"
            f"To determine which engagement to use (`<engagement>` in paths below):\n"
            f"1. If the current working directory is inside an engagement directory, use that engagement\n"
            f"2. If there's only one engagement, use it automatically\n"
            f"3. Otherwise, ask the user which engagement to target"
        )
    else:
        engagement_resolution = (
            "## Engagement resolution\n\n"
            "No engagements found. Run `sl-ot-tools init engagement <name>` first, "
            "then `sl-ot-tools setup` to reinstall skills."
        )

    installed = 0
    skipped = 0
    for template_file in templates_dir.glob("*.md"):
        content = template_file.read_text(encoding="utf-8")
        content = content.replace("{{COMPANY_DIR}}", "_company")
        content = content.replace("{{PROMPTS_DIR}}", str(PROMPTS_DIR))
        content = content.replace("{{ENGAGEMENT_RESOLUTION}}", engagement_resolution)
        content = content.replace("{{COMPANY_NAME}}", company_name)

        target_file = target_dir / template_file.name

        # Check for user modifications before overwriting
        if target_file.exists() and not force:
            existing = target_file.read_text(encoding="utf-8")
            if existing == content:
                installed += 1  # already up to date
                continue
            # File differs — could be user edits or stale template output.
            # Back up and warn rather than silently overwriting.
            backup_file = target_file.with_suffix(".md.bak")
            backup_file.write_text(existing, encoding="utf-8")
            print(f"  Updated: {template_file.name} (backup: {backup_file.name})")

        target_file.write_text(content, encoding="utf-8")
        installed += 1

    if skipped:
        print(f"Installed {installed} skills, skipped {skipped} with local edits")
        print(f"  Use 'sl-ot-tools setup --force' to overwrite all skills")
    else:
        print(f"Installed {installed} skills to .claude/commands/")


# ── helpers ───────────────────────────────────────────────────

def _write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


# ── main ──────────────────────────────────────────────────────

def main():
    args = sys.argv[1:]

    if not args or args[0] in ("-h", "--help"):
        print(f"sl-ot-tools v{__version__}")
        print()
        print("Commands:")
        print("  init company <slug>      Create a new company repo")
        print("  init engagement <name>   Create a new engagement directory")
        print("  setup                    Update skills and viewer (re-run safely)")
        print("    --reconfigure          Re-prompt for user config values")
        print("    --force                Overwrite modified skill files")
        print("  settings                 Configure user-level settings")
        print("  check                    Verify installation and config")
        print("  generate-viewer          Regenerate org chart viewer")
        print()
        print("  --version                Show version")
        sys.exit(0)

    if args[0] == "--version":
        print(f"sl-ot-tools v{__version__}")
        sys.exit(0)

    if args[0] == "init":
        if len(args) < 3:
            print("Usage: sl-ot-tools init <company|engagement> <name>")
            sys.exit(1)
        if args[1] == "company":
            cmd_init_company(args[2])
        elif args[1] == "engagement":
            cmd_init_engagement(args[2])
        else:
            print(f"Unknown init type: {args[1]}")
            print("Usage: sl-ot-tools init <company|engagement> <name>")
            sys.exit(1)

    elif args[0] == "settings":
        from .config.settings import init_settings
        init_settings()

    elif args[0] == "setup":
        reconfigure = "--reconfigure" in args
        force_skills = "--force" in args
        cmd_setup(reconfigure=reconfigure, force_skills=force_skills)

    elif args[0] == "check":
        success = cmd_check()
        sys.exit(0 if success else 1)

    elif args[0] == "generate-viewer":
        cmd_generate_viewer()

    else:
        print(f"Unknown command: {args[0]}")
        print("Run 'sl-ot-tools --help' for usage")
        sys.exit(1)


if __name__ == "__main__":
    main()
